// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace DBChatHistory.DBChatHistory;

public partial class ChatContext : DbContext
{
    public ChatContext(DbContextOptions<ChatContext> options)
        : base(options)
    {
    }

    public virtual DbSet<ChatHistory> ChatHistories { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<ChatHistory>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__ChatHist__3214EC0760ED4F26");

            entity.ToTable("ChatHistory");

            entity.Property(e => e.Id).ValueGeneratedNever();
            entity.Property(e => e.Key)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.SessionId).HasMaxLength(50);
            entity.Property(e => e.TimeStamp).HasDefaultValueSql("(getdate())");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}