// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DBChatHistory.DBChatHistory;

public partial class ChatHistory
{
    public int Id { get; set; }

    public string Key { get; set; }

    public string SessionId { get; set; }

    public DateTime TimeStamp { get; set; }

    public string SerializedMessage { get; set; }

    public string Message { get; set; }
}