//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RAGDataIngestionWPF.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RAGDataIngestionWPF.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RAGDataIngestionWPF.
        /// </summary>
        public static string AppDisplayName {
            get {
                return ResourceManager.GetString("AppDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blank.
        /// </summary>
        public static string BlankPageTitle {
            get {
                return ResourceManager.GetString("BlankPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Knowledge Source Ingestion.
        /// </summary>
        public static string DataGridPageTitle {
            get {
                return ResourceManager.GetString("DataGridPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sample Orders.
        /// </summary>
        public static string ListDetailsListDescription {
            get {
                return ResourceManager.GetString("ListDetailsListDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ListDetails.
        /// </summary>
        public static string ListDetailsPageTitle {
            get {
                return ResourceManager.GetString("ListDetailsPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to log in.
        /// </summary>
        public static string LogInButton {
            get {
                return ResourceManager.GetString("LogInButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log In.
        /// </summary>
        public static string LogInPageTitle {
            get {
                return ResourceManager.GetString("LogInPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agentic Chat.
        /// </summary>
        public static string MainPageTitle {
            get {
                return ResourceManager.GetString("MainPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings page placeholder text.  Your app description goes here..
        /// </summary>
        public static string SettingsPageAboutText {
            get {
                return ResourceManager.GetString("SettingsPageAboutText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agent Framework Implementation.
        /// </summary>
        public static string SettingsPageAboutTitle {
            get {
                return ResourceManager.GetString("SettingsPageAboutTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Chat History Context Injection.
        /// </summary>
        public static string SettingsPageChatHistoryContextEnabledLabel {
            get {
                return ResourceManager.GetString("SettingsPageChatHistoryContextEnabledLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AI Settings.
        /// </summary>
        public static string SettingsPageChatHistoryGroupBoxTitle {
            get {
                return ResourceManager.GetString("SettingsPageChatHistoryGroupBoxTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chat history settings saved..
        /// </summary>
        public static string SettingsPageChatHistorySaveStatus {
            get {
                return ResourceManager.GetString("SettingsPageChatHistorySaveStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chat History.
        /// </summary>
        public static string SettingsPageChatHistoryTitle {
            get {
                return ResourceManager.GetString("SettingsPageChatHistoryTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chat Model.
        /// </summary>
        public static string SettingsPageChatModelLabel {
            get {
                return ResourceManager.GetString("SettingsPageChatModelLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Theme.
        /// </summary>
        public static string SettingsPageChooseThemeText {
            get {
                return ResourceManager.GetString("SettingsPageChooseThemeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection String.
        /// </summary>
        public static string SettingsPageConnectionStringLabel {
            get {
                return ResourceManager.GetString("SettingsPageConnectionStringLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Embeddings Model.
        /// </summary>
        public static string SettingsPageEmbeddingsModelLabel {
            get {
                return ResourceManager.GetString("SettingsPageEmbeddingsModelLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log out.
        /// </summary>
        public static string SettingsPageLogOutButtonText {
            get {
                return ResourceManager.GetString("SettingsPageLogOutButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max Context Messages.
        /// </summary>
        public static string SettingsPageMaxContextMessagesLabel {
            get {
                return ResourceManager.GetString("SettingsPageMaxContextMessagesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max Context Tokens.
        /// </summary>
        public static string SettingsPageMaxContextTokensLabel {
            get {
                return ResourceManager.GetString("SettingsPageMaxContextTokensLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personalization.
        /// </summary>
        public static string SettingsPagePersonalizationTitle {
            get {
                return ResourceManager.GetString("SettingsPagePersonalizationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy Statement.
        /// </summary>
        public static string SettingsPagePrivacyStatementText {
            get {
                return ResourceManager.GetString("SettingsPagePrivacyStatementText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark.
        /// </summary>
        public static string SettingsPageRadioButtonDarkTheme {
            get {
                return ResourceManager.GetString("SettingsPageRadioButtonDarkTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light.
        /// </summary>
        public static string SettingsPageRadioButtonLightTheme {
            get {
                return ResourceManager.GetString("SettingsPageRadioButtonLightTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        public static string SettingsPageRadioButtonWindowsDefaultTheme {
            get {
                return ResourceManager.GetString("SettingsPageRadioButtonWindowsDefaultTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable RAG Knowledge Context Injection.
        /// </summary>
        public static string SettingsPageRagKnowledgeEnabledLabel {
            get {
                return ResourceManager.GetString("SettingsPageRagKnowledgeEnabledLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Chat History Settings.
        /// </summary>
        public static string SettingsPageSaveChatHistoryButtonText {
            get {
                return ResourceManager.GetString("SettingsPageSaveChatHistoryButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string SettingsPageTitle {
            get {
                return ResourceManager.GetString("SettingsPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        public static string SettingsPageUserTitle {
            get {
                return ResourceManager.GetString("SettingsPageUserTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blank.
        /// </summary>
        public static string ShellBlankPage {
            get {
                return ResourceManager.GetString("ShellBlankPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingestion.
        /// </summary>
        public static string ShellDataGridPage {
            get {
                return ResourceManager.GetString("ShellDataGridPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go back.
        /// </summary>
        public static string ShellGoBackButton {
            get {
                return ResourceManager.GetString("ShellGoBackButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open or close navigation.
        /// </summary>
        public static string ShellHamburgerButtonName {
            get {
                return ResourceManager.GetString("ShellHamburgerButtonName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ListDetails.
        /// </summary>
        public static string ShellListDetailsPage {
            get {
                return ResourceManager.GetString("ShellListDetailsPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main.
        /// </summary>
        public static string ShellMainPage {
            get {
                return ResourceManager.GetString("ShellMainPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string ShellSettingsPage {
            get {
                return ResourceManager.GetString("ShellSettingsPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WebView.
        /// </summary>
        public static string ShellWebViewPage {
            get {
                return ResourceManager.GetString("ShellWebViewPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong during the login, please try again..
        /// </summary>
        public static string StatusLoginFails {
            get {
                return ResourceManager.GetString("StatusLoginFails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no internet connection, please connect to the internet and try again..
        /// </summary>
        public static string StatusNoNetworkAvailable {
            get {
                return ResourceManager.GetString("StatusNoNetworkAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User is unauthorized.
        /// </summary>
        public static string StatusUnauthorized {
            get {
                return ResourceManager.GetString("StatusUnauthorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back (Alt + Left).
        /// </summary>
        public static string WebViewPageBackButtonTooltip {
            get {
                return ResourceManager.GetString("WebViewPageBackButtonTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page failed to load. Check connection and retry..
        /// </summary>
        public static string WebViewPageFaildedMessage {
            get {
                return ResourceManager.GetString("WebViewPageFaildedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forward (Alt + Right).
        /// </summary>
        public static string WebViewPageForwardButtonTooltip {
            get {
                return ResourceManager.GetString("WebViewPageForwardButtonTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        public static string WebViewPageLoadingText {
            get {
                return ResourceManager.GetString("WebViewPageLoadingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open in browser (Ctrl + T).
        /// </summary>
        public static string WebViewPageOpenInBrowserButtonTooltip {
            get {
                return ResourceManager.GetString("WebViewPageOpenInBrowserButtonTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh (F5).
        /// </summary>
        public static string WebViewPageRefreshButtonTooltip {
            get {
                return ResourceManager.GetString("WebViewPageRefreshButtonTooltip", resourceCulture);
            }
        }
    }
}
