// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using DataIngestionLib.EFModels;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace DataIngestionLib.EFModels
{
    public partial class AIRemoteRagContext
    {
        private IAIRemoteRagContextProcedures _procedures;

        public virtual IAIRemoteRagContextProcedures Procedures
        {
            get
            {
                if (_procedures is null) _procedures = new AIRemoteRagContextProcedures(this);
                return _procedures;
            }
            set
            {
                _procedures = value;
            }
        }

        public IAIRemoteRagContextProcedures GetProcedures()
        {
            return Procedures;
        }
    }

    public partial class AIRemoteRagContextProcedures : IAIRemoteRagContextProcedures
    {
        private readonly AIRemoteRagContext _context;

        public AIRemoteRagContextProcedures(AIRemoteRagContext context)
        {
            _context = context;
        }

        public virtual async Task<List<Search_FullTextResult>> Search_FullTextAsync(string query, int? topN, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "Query",
                    Size = 8000,
                    Value = query ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                new SqlParameter
                {
                    ParameterName = "TopN",
                    Value = topN ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                parameterreturnValue,
            };
            var _ = await _context.SqlQueryAsync<Search_FullTextResult>("EXEC @returnValue = [dbo].[Search_FullText] @Query = @Query, @TopN = @TopN", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<List<Search_HybridResult>> Search_HybridAsync(string query, byte[] queryEmbedding, int? topN, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "Query",
                    Size = 8000,
                    Value = query ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                new SqlParameter
                {
                    ParameterName = "QueryEmbedding",
                    Size = 4104,
                    Value = queryEmbedding ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.VarBinary,
                },
                new SqlParameter
                {
                    ParameterName = "TopN",
                    Value = topN ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                parameterreturnValue,
            };
            var _ = await _context.SqlQueryAsync<Search_HybridResult>("EXEC @returnValue = [dbo].[Search_Hybrid] @Query = @Query, @QueryEmbedding = @QueryEmbedding, @TopN = @TopN", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<List<Search_RAG_AdvancedResult>> Search_RAG_AdvancedAsync(string queryText, string searchType, double? minScore, int? maxResults, DateTime? dateFrom, DateTime? dateTo, string keywords, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "QueryText",
                    Size = -1,
                    Value = queryText ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                new SqlParameter
                {
                    ParameterName = "SearchType",
                    Size = 20,
                    Value = searchType ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.VarChar,
                },
                new SqlParameter
                {
                    ParameterName = "MinScore",
                    Value = minScore ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Float,
                },
                new SqlParameter
                {
                    ParameterName = "MaxResults",
                    Value = maxResults ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                new SqlParameter
                {
                    ParameterName = "DateFrom",
                    Scale = 7,
                    Value = dateFrom ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.DateTime2,
                },
                new SqlParameter
                {
                    ParameterName = "DateTo",
                    Scale = 7,
                    Value = dateTo ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.DateTime2,
                },
                new SqlParameter
                {
                    ParameterName = "Keywords",
                    Size = 2000,
                    Value = keywords ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                parameterreturnValue,
            };
            var _ = await _context.SqlQueryAsync<Search_RAG_AdvancedResult>("EXEC @returnValue = [dbo].[Search_RAG_Advanced] @QueryText = @QueryText, @SearchType = @SearchType, @MinScore = @MinScore, @MaxResults = @MaxResults, @DateFrom = @DateFrom, @DateTo = @DateTo, @Keywords = @Keywords", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<List<Search_SemanticKeyPhrasesResult>> Search_SemanticKeyPhrasesAsync(int? documentId, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "DocumentId",
                    Value = documentId ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                parameterreturnValue,
            };
            var _ = await _context.SqlQueryAsync<Search_SemanticKeyPhrasesResult>("EXEC @returnValue = [dbo].[Search_SemanticKeyPhrases] @DocumentId = @DocumentId", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<List<sp_Generate_EmbeddingsResult>> sp_Generate_EmbeddingsAsync(string query, OutputParameter<byte[]> embedding, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterEmbedding = new SqlParameter
            {
                ParameterName = "Embedding",
                Size = 4104,
                Direction = System.Data.ParameterDirection.InputOutput,
                Value = embedding?._value ?? Convert.DBNull,
                SqlDbType = System.Data.SqlDbType.VarBinary,
            };
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "Query",
                    Size = -1,
                    Value = query ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                parameterEmbedding,
                parameterreturnValue,
            };
            var _ = await _context.SqlQueryAsync<sp_Generate_EmbeddingsResult>("EXEC @returnValue = [dbo].[sp_Generate_Embeddings] @Query = @Query, @Embedding = @Embedding OUTPUT", sqlParameters, cancellationToken);

            embedding?.SetValue(parameterEmbedding.Value);
            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<List<sp_GenerateKeywordsResult>> sp_GenerateKeywordsAsync(Guid? chunkId, string content, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "ChunkId",
                    Value = chunkId ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.UniqueIdentifier,
                },
                new SqlParameter
                {
                    ParameterName = "Content",
                    Size = -1,
                    Value = content ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                parameterreturnValue,
            };
            var _ = await _context.SqlQueryAsync<sp_GenerateKeywordsResult>("EXEC @returnValue = [dbo].[sp_GenerateKeywords] @ChunkId = @ChunkId, @Content = @Content", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<List<sp_LearnDocs_Search_VectorResult>> sp_LearnDocs_Search_VectorAsync(string queryText, int? topN, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "QueryText",
                    Size = -1,
                    Value = queryText ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                new SqlParameter
                {
                    ParameterName = "TopN",
                    Value = topN ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                parameterreturnValue,
            };
            var _ = await _context.SqlQueryAsync<sp_LearnDocs_Search_VectorResult>("EXEC @returnValue = [dbo].[sp_LearnDocs_Search_Vector] @QueryText = @QueryText, @TopN = @TopN", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<List<sp_Remote_Search_VectorResult>> sp_Remote_Search_VectorAsync(string queryText, int? topN, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "QueryText",
                    Size = -1,
                    Value = queryText ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                new SqlParameter
                {
                    ParameterName = "TopN",
                    Value = topN ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                parameterreturnValue,
            };
            var _ = await _context.SqlQueryAsync<sp_Remote_Search_VectorResult>("EXEC @returnValue = [dbo].[sp_Remote_Search_Vector] @QueryText = @QueryText, @TopN = @TopN", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<List<sp_Update_md_EmbeddingsResult>> sp_Update_md_EmbeddingsAsync(OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                parameterreturnValue,
            };
            var _ = await _context.SqlQueryAsync<sp_Update_md_EmbeddingsResult>("EXEC @returnValue = [dbo].[sp_Update_md_Embeddings]", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }
    }
}
