// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace DataIngestionLib.EFModels;

public partial class AIRemoteRagContext : DbContext
{
    public AIRemoteRagContext(DbContextOptions<AIRemoteRagContext> options)
        : base(options)
    {
    }

    public virtual DbSet<MdDocument> MdDocuments { get; set; }

    public virtual DbSet<MdDocumentChunk> MdDocumentChunks { get; set; }

    public virtual DbSet<RemoteRag> RemoteRags { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<MdDocument>(entity =>
        {
            entity.HasKey(e => e.DocId);

            entity.ToTable("md_documents");

            entity.HasIndex(e => e.MsDate, "IX_md_documents_ms_date");

            entity.HasIndex(e => e.FilePath, "UQ_md_documents_file_path").IsUnique();

            entity.Property(e => e.DocId)
                .HasDefaultValueSql("(newsequentialid())", "DF_md_documents_doc_id")
                .HasColumnName("doc_id");
            entity.Property(e => e.Author)
                .HasMaxLength(256)
                .HasColumnName("author");
            entity.Property(e => e.ContentHash)
                .IsRequired()
                .HasMaxLength(64)
                .HasColumnName("content_hash");
            entity.Property(e => e.ContentNormalized).HasColumnName("content_normalized");
            entity.Property(e => e.ContentRaw)
                .IsRequired()
                .HasColumnName("content_raw");
            entity.Property(e => e.Description)
                .HasMaxLength(2048)
                .HasColumnName("description");
            entity.Property(e => e.FileName)
                .IsRequired()
                .HasMaxLength(260)
                .HasColumnName("file_name");
            entity.Property(e => e.FilePath)
                .IsRequired()
                .HasMaxLength(512)
                .HasColumnName("file_path");
            entity.Property(e => e.IngestedAt)
                .HasDefaultValueSql("(sysutcdatetime())", "DF_md_documents_ingested_at")
                .HasColumnName("ingested_at");
            entity.Property(e => e.MsDate).HasColumnName("ms_date");
            entity.Property(e => e.MsTopic)
                .HasMaxLength(256)
                .HasColumnName("ms_topic");
            entity.Property(e => e.Title)
                .HasMaxLength(512)
                .HasColumnName("title");
            entity.Property(e => e.UpdatedAt).HasColumnName("updated_at");
            entity.Property(e => e.WordCount).HasColumnName("word_count");
            entity.Property(e => e.YamlFrontMatter)
                .HasMaxLength(4000)
                .HasColumnName("yaml_front_matter");
        });

        modelBuilder.Entity<MdDocumentChunk>(entity =>
        {
            entity.ToTable("md_document_chunks");

            entity.HasIndex(e => new { e.DocId, e.ChunkType }, "IX_md_document_chunks_doc_id_chunk_type");

            entity.HasIndex(e => e.Embeddings, "VectorIndex-20260327-210733");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.ChunkId)
                .HasDefaultValueSql("(newsequentialid())", "DF_md_document_chunks_chunk_id")
                .HasColumnName("chunk_id");
            entity.Property(e => e.ChunkIndex).HasColumnName("chunk_index");
            entity.Property(e => e.ChunkType)
                .IsRequired()
                .HasMaxLength(16)
                .HasDefaultValue("text", "DF_md_document_chunks_chunk_type")
                .HasColumnName("chunk_type");
            entity.Property(e => e.Content)
                .IsRequired()
                .HasColumnName("content");
            entity.Property(e => e.ContentHash)
                .HasComment("Used for change detection")
                .HasColumnName("content_hash");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(sysutcdatetime())", "DF_md_document_chunks_created_at")
                .HasColumnName("created_at");
            entity.Property(e => e.DocId).HasColumnName("doc_id");
            entity.Property(e => e.Embeddings)
                .HasMaxLength(1024)
                .HasColumnName("embeddings");
            entity.Property(e => e.Heading)
                .HasMaxLength(512)
                .HasColumnName("heading");
            entity.Property(e => e.HeadingLevel).HasColumnName("heading_level");
            entity.Property(e => e.HeadingPath)
                .HasMaxLength(1024)
                .HasColumnName("heading_path");
            entity.Property(e => e.Keywords).HasColumnName("keywords");
            entity.Property(e => e.Language)
                .HasMaxLength(64)
                .HasColumnName("language");
            entity.Property(e => e.Summary)
                .HasMaxLength(4000)
                .HasColumnName("summary");
            entity.Property(e => e.TokenCount).HasColumnName("token_count");
        });

        modelBuilder.Entity<RemoteRag>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__RemoteRA__3214EC075F4501BD");

            entity.ToTable("RemoteRAG", tb =>
                {
                    tb.HasTrigger("tr_generate_embeddings");
                    tb.HasTrigger("trg_RemoteRAG_CalculateScore");
                });

            entity.HasIndex(e => e.MsDate, "IX_RemoteRAG_ms_date").IsDescending();

            entity.HasIndex(e => e.Score, "IX_RemoteRAG_score").IsDescending();

            entity.HasIndex(e => e.UpdatedAt, "IX_RemoteRAG_updated_at_filtered")
                .IsDescending()
                .HasFilter("([embedding] IS NOT NULL)");

            entity.HasIndex(e => e.DocumentId, "UX_RemoteRAG_document_id").IsUnique();

            entity.HasIndex(e => e.OgUrl, "UX_RemoteRAG_og_url").IsUnique();

            entity.Property(e => e.Description)
                .IsRequired()
                .HasColumnName("description");
            entity.Property(e => e.DocumentId)
                .HasDefaultValueSql("(newid())", "DF__RemoteRAG__DocId__4F47C5E3")
                .HasColumnName("document_id");
            entity.Property(e => e.Embedding)
                .HasMaxLength(1024)
                .HasColumnName("embedding");
            entity.Property(e => e.Keywords)
                .HasMaxLength(500)
                .HasColumnName("keywords");
            entity.Property(e => e.MsDate).HasColumnName("ms_date");
            entity.Property(e => e.OgUrl)
                .IsRequired()
                .HasMaxLength(500)
                .HasColumnName("og_url");
            entity.Property(e => e.Score).HasColumnName("score");
            entity.Property(e => e.Summary).HasColumnName("summary");
            entity.Property(e => e.Title)
                .IsRequired()
                .HasMaxLength(450)
                .HasColumnName("title");
            entity.Property(e => e.TokenCount).HasColumnName("token_count");
            entity.Property(e => e.UpdatedAt).HasColumnName("updated_at");
            entity.Property(e => e.Version).HasColumnName("version");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}