// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using DataIngestionLib.EFModels;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace DataIngestionLib.EFModels
{
    public partial interface IAIRemoteRagContextProcedures
    {
        Task<List<Search_FullTextResult>> Search_FullTextAsync(string query, int? topN, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<Search_HybridResult>> Search_HybridAsync(string query, byte[] queryEmbedding, int? topN, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<Search_RAG_AdvancedResult>> Search_RAG_AdvancedAsync(string queryText, string searchType, double? minScore, int? maxResults, DateTime? dateFrom, DateTime? dateTo, string keywords, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<Search_SemanticKeyPhrasesResult>> Search_SemanticKeyPhrasesAsync(int? documentId, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<sp_Generate_EmbeddingsResult>> sp_Generate_EmbeddingsAsync(string query, OutputParameter<byte[]> embedding, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<sp_GenerateKeywordsResult>> sp_GenerateKeywordsAsync(Guid? chunkId, string content, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<sp_LearnDocs_Search_VectorResult>> sp_LearnDocs_Search_VectorAsync(string queryText, int? topN, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<sp_Remote_Search_VectorResult>> sp_Remote_Search_VectorAsync(string queryText, int? topN, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<sp_Update_md_EmbeddingsResult>> sp_Update_md_EmbeddingsAsync(OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
    }
}
