// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DataIngestionLib.EFModels;

public partial class MdDocument
{
    public Guid DocId { get; set; }

    public string FilePath { get; set; }

    public string FileName { get; set; }

    public string Title { get; set; }

    public string Description { get; set; }

    public string Author { get; set; }

    public DateOnly? MsDate { get; set; }

    public string MsTopic { get; set; }

    public string YamlFrontMatter { get; set; }

    public string ContentRaw { get; set; }

    public string ContentNormalized { get; set; }

    public string ContentHash { get; set; }

    public int? WordCount { get; set; }

    public DateTime IngestedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }
}