// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.Data.SqlTypes;

namespace DataIngestionLib.EFModels;

public partial class MdDocumentChunk
{
    public int Id { get; set; }

    public Guid ChunkId { get; set; }

    public Guid DocId { get; set; }

    public int ChunkIndex { get; set; }

    public string HeadingPath { get; set; }

    public string Heading { get; set; }

    public byte? HeadingLevel { get; set; }

    public string ChunkType { get; set; }

    public string Language { get; set; }

    public string Content { get; set; }

    public int? TokenCount { get; set; }

    public string Keywords { get; set; }

    public string Summary { get; set; }

    public DateTime CreatedAt { get; set; }

    public SqlVector<float>? Embeddings { get; set; }

    /// <summary>
    /// Used for change detection
    /// </summary>
    public string ContentHash { get; set; }
}