// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.Data.SqlTypes;

namespace DataIngestionLib.EFModels;

public partial class RemoteRag
{
    public int Id { get; set; }

    public Guid DocumentId { get; set; }

    public string OgUrl { get; set; }

    public DateTime MsDate { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public string Title { get; set; }

    public string Description { get; set; }

    public string Keywords { get; set; }

    public string Summary { get; set; }

    public SqlVector<float>? Embedding { get; set; }

    public int? TokenCount { get; set; }

    public int? Version { get; set; }

    public double? Score { get; set; }
}