// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace DataIngestionLib.EFModels
{
    public partial class Search_SemanticKeyPhrasesResult
    {
        public int column_id { get; set; }
        public long document_key { get; set; }
        [StringLength(4000)]
        public string keyphrase { get; set; }
        public float score { get; set; }
    }
}
